### ISSUE TITLE
PEx -> Luckperms Conversion of ~1600 players causes server to crash

### ISSUE THREAD

**Issue by spencer-wild** [LuckPerms/migration#1]
Spigot Version: 1.8.8
LuckPerms Version: 5.3.27

Steps to reproduce:
1. Load the server with spigot 1.8.8, luckperms 5.3.27, and the large database we have along with the migration jar.
2. Attempt to migrate it

Originally, it gets through all the groups and about 400 people, but if you run it again a few times after it crashes over and over it gets up to about 745 then stops going further. The number 745 is based on looking at the database that luckperms has.

Ways I have tried to resolve:
1. Removing/disabling all other plugins
2. Repeatedly running it over and over to see if this would result in it finishing

Log of the crash is attached. Let me know if I can provide additional information.

Edit to add: https://pastebin.com/7hLFNTUb <- log in pastebin format in case you don't want to download
[2021-04-20-7.log](https://github.com/LuckPerms/migration/files/6340311/2021-04-20-7.log)

**Comment by kaiarne** [comment]
Same problem, server times out and shuts down after approx. 1600 (of 3700) users. 
Disabling all plugins and giving the server Xmx=6500M Memory let it convert ~3000 users before it shut down.
Checking the database showed that the progress very much slows down after 1500 users. In console PaperMC is spamming "timed" warnings.

So my workaround was to _temporarily_ set "timeout-time" in spigot.yml to a high value (rising from standard 240 to 888 was sufficient).

**Comment by lucko** [comment]
oops, shoudl be fixed in 097db6055975e94dbdacac2d8c49d7b049e8fe77
